import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container mx-auto px-12">
          <div className="flex m-2 justify-between items-center text-xl font-bold py-4">
            <Link href="/">Home</Link>
          </div>
          {children}
        </div>
      </body>
    </html>
  );
}
